SmartBear/soapui

soapui/pom.xml
soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/BaseAnalyticsProvider.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/GoogleAnalyticsProvider.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/GoogleAnalyticsProviderFactory.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/KeenIOProvider.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/KeenIOProviderFactory.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/LogTabAnalyticsProvider.java

Sending analytics added into SoapUI 5.1.2 OS

---

soapui/src/main/java/com/eviware/soapui/actions/ImportPackedProject.java

Maked by https://smartbear.atlassian.net/browse/SOAP-3364 - NullPointerException when cancel import packed project
Solution: add validation to null

Add validation to null

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/HelpUrls.java

http://www.soapui.org/functional-testing/teststep-reference/conditional-goto/conditional-goto.html

Replaced URL

---

soapui/src/main/java/com/eviware/soapui/mockaswar/MockAsWarServlet.java
soapui/src/main/java/com/eviware/soapui/tools/MockAsWar.java

Maked by JIRA bug  SOAP-3315 The "NullPointerException" error occurs when running servlet "MockAsWarServlet" (https://smartbear.atlassian.net/browse/SOAP-3315)
Solution : add validation variables to Null Pointer Exception

Soap 3315 the null pointer exception error

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/HelpUrls.java
soapui/src/test/java/com/eviware/soapui/support/HelpUrlChecker.java

Changed faulty URLs.
Added URLchecker.

SOAP-3381 Incorrect or broken help links

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/soapui/SecurityTestRunnerAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/project/SimpleDialog.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/project/StartHermesJMS.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/HelpUrls.java

Help url fixes

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/TestAssertionRegistry.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathAssertionBase.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathContentAssertion.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathCountAssertion.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathExistenceAssertion.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathRegExAssertion.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/json/JsonPathRexExAssertionConfigurationDialog.java

https://smartbear.atlassian.net/browse/SOAP-3593

SOAP-3593 - Add JSON Path based asserions to Open Source

---

RELEASENOTES.txt

Adding info on bundled plugins + a note about plugin framework.

Updating the ReleaseNotes 

---

soapui-installer/src/install4j/SoapUI.install4j

https://smartbear.atlassian.net/browse/SOAPUIOS-161

SOAPUIOS-161 Setting access for wsi test tools directory

---

soapui-installer/src/dist/bin/soapui.bat
soapui-installer/src/dist/bin/soapui.sh
soapui-installer/src/dist_standalone/bin/soapui.bat
soapui-installer/src/dist_standalone/bin/soapui.sh
soapui/src/main/java/com/eviware/soapui/plugins/ProductBodyguard.java

https://smartbear.atlassian.net/browse/SOAPUIOS-165

SOAPUIOS-165 Min heap free ratio max heap free ratio values correction

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/analytics/AnalyticsHelper.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUITestCaseRunner.java

https://smartbear.atlassian.net/browse/SOAPUIOS-188

SOAPUIOS-188 correct analytics initializing

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/teststeps/JdbcRequestTestStepDesktopPanel.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/teststeps/JdbcResponse.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/JdbcRequestTestStep.java
soapui/src/main/java/com/eviware/soapui/support/xml/XmlUtils.java
soapui/src/main/resources/com/eviware/soapui/impl/wsdl/panels/teststeps/Bundle.properties
soapui/src/main/xsd/soapui/soapui.xsd
soapui/src/test/java/com/eviware/soapui/impl/wsdl/support/wss/entries/SignatureEntryTest.java

https://smartbear.atlassian.net/browse/SOAPUIOS-190

Soapuios 190 jdbc request step converts sql column names to upper case

---

soapui/src/main/java/com/eviware/soapui/support/swing/JTextComponentPopupMenu.java

https://smartbear.atlassian.net/browse/SOAPUIOS-201

SOAPUIOS-201 - Xml editor's context menu has double items

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/JdbcMessageExchange.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/basic/GroovyScriptAssertion.java

https://smartbear.atlassian.net/browse/SOAPUIOS-200

SOAPUIOS-200 - Groovy Assertions BUG in JDBC request

---

soapui/src/main/java/com/eviware/soapui/impl/rest/support/RestRequestParamsPropertyHolder.java

Changes from https://github.com/SmartBear/axm/pull/3527.

SOAP-573 Rest headers not updated

---

soapui/src/main/java/com/eviware/soapui/impl/rest/support/RestRequestParamsPropertyHolder.java
soapui/src/main/java/com/eviware/soapui/security/assertion/ValidHttpStatusCodesAssertion.java
soapui/src/main/java/com/eviware/soapui/support/ModelItemNamer.java

SOAPUIOS-208 Import postman release

---

soapui/src/main/java/com/eviware/soapui/security/assertion/InvalidHttpStatusCodesAssertion.java

https://smartbear.atlassian.net/browse/SOAPUIOS-227

SOAPUIOS-227 Not all Postman requests imported

---

soapui/src/main/java/com/eviware/soapui/impl/actions/RestServiceBuilder.java

https://smartbear.atlassian.net/browse/SOAPUIOS-228
The change was introduced in Ready! API commit https://github.com/SmartBear/axm/commit/eaa7b42e54debbfbfa2dacf36511377e9ab9b129.

SOAPUIOS-228 Create resources with unique names

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/teststeps/assertions/basic/ResponseSLAAssertion.java
soapui/src/main/java/com/eviware/x/impl/swing/SwingDialogs.java

https://smartbear.atlassian.net/browse/SOAPUIOS-234

SOAPUIOS-234 store SLA value after clicking Cancel.

---

soapui/src/main/java/com/eviware/soapui/analytics/AnalyticsHelper.java

https://smartbear.atlassian.net/browse/SOAPUIOS-241

Soapuios-241 analytics fix

---

soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/DelayTestStepParser.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/JsonRecipeParser.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/TestStepNames.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/teststeps/DelayTestStepStruct.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/teststeps/TestStepStructAdapter.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/teststeps/TestStepTypeResolver.java
soapui-testserver-api/src/main/resources/test-recipe-schema.json
soapui-testserver-api/src/test/java/com/smartbear/ready/recipe/DelayTestStepParsingTest.java
soapui-testserver-api/src/test/resources/test-recipes/delay-test-step.json

Just a coy of the same PR on Ready! API

TSERV-241: Adding support for delay test step in recipes

---

soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/JsonRecipeParser.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/teststeps/TestCaseStruct.java
soapui-testserver-api/src/main/resources/test-recipe-schema.json
soapui-testserver-api/src/test/java/com/smartbear/ready/recipe/TestCaseOptionsParsingTest.java
soapui-testserver-api/src/test/resources/test-recipes/test-case-level-options.json

Adding another piece which is present in Ready! API but was missing in SoapUI

Adding the support for TestCase level properties

---

pom.xml
soapui/pom.xml
soapui/src/main/java/com/eviware/soapui/actions/SoapUIPreferencesAction.java
soapui/src/main/java/com/eviware/soapui/support/JsonPathFacade.java

See screenshot for new layout of global preferences; selecting an item from the list on the left selects the corresponding settings on the right. This works better on Mac but I'm not sure what it looks like on Windows.

Updated to use java 1.8 and fixed layout of global preferences dialog

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/submit/transports/http/HttpClientRequestTransport.java

This change is related to pull request 256 that was merged some time ago. I think I introduced  a compilation error while fixing formatting. There was a parentheses missing. I noticed this will taking the latest version after the pull request was merged and testing out my changes.
Could you merge this so others are able to get latest and compile successfully

fixing compilation error

---

soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/JsonRecipeParser.java
soapui-testserver-api/src/main/java/com/smartbear/ready/recipe/teststeps/TestCaseStruct.java
soapui-testserver-api/src/main/resources/test-recipe-schema.json
soapui-testserver-api/src/test/java/com/smartbear/ready/recipe/TestCaseOptionsParsingTest.java
soapui-testserver-api/src/test/resources/test-recipes/test-case-level-options.json

Adding name parameter to recipe

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/wsdl/UrlWsdlLoader.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/wsdl/WsdlLoader.java

https://smartbear.atlassian.net/browse/SOAPUIOS-217

SOAPUIOS-217 cant use in username and password when creating soap project

---

soapui-installer/src/install4j/SoapUI.install4j

https://smartbear.atlassian.net/browse/SOAPUIOS-278

SOAPUIOS-278 Fix bundled jre

---

soapui-installer/pom.xml
soapui-maven-plugin-tester/pom.xml
soapui-maven-plugin/pom.xml
soapui-system-test/pom.xml
soapui-testserver-api/pom.xml
soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/wsdl/UrlWsdlLoader.java

https://smartbear.atlassian.net/browse/SOAPUIOS-287

SOAPUIOS-287 Error if create new project from WSDL

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java

https://smartbear.atlassian.net/browse/SOAPUIOS-294

SOAPUIOS-294 No event for the launch of the product

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java

https://smartbear.atlassian.net/browse/SOAPUIOS-295

SOAPUIOS-295 double ExitWithoutSave event

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/actions/SaveAllProjectsAction.java
soapui/src/main/java/com/eviware/soapui/impl/actions/NewEmptyProjectAction.java
soapui/src/main/java/com/eviware/soapui/impl/actions/NewRestProjectAction.java
soapui/src/main/java/com/eviware/soapui/impl/actions/NewWsdlProjectAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-297

SOAPUIOS-297 Toolbar events are sent even if user doesn't do these action

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/testcase/WsdlTestCaseDesktopPanel.java

https://smartbear.atlassian.net/browse/SOAPUIOS-306

SOAPUIOS-306 Fix event

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/rest/actions/project/NewRestServiceAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-304

SOAPUIOS-304 Fix event

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java

https://smartbear.atlassian.net/browse/SOAPUIOS-303

SOAPUIOS-303 Change event params

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/actions/SaveAllProjectsAction.java
soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java

https://smartbear.atlassian.net/browse/SOAPUIOS-300

SOAPUIOS-300 Wrong event is sent for "save all projects" action

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/mockservice/StartMinimizedMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/mockservice/StopMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/mock/WsdlMockServiceDesktopPanel.java

https://smartbear.atlassian.net/browse/SOAPUIOS-309

SOAPUIOS-309 Start/stop mock events

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/testcase/AddWsdlTestStepAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/teststep/InsertWsdlTestStepAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-314

SOAPUIOS-314 Handle test step insertion

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/rest/actions/mock/AddRestRequestToMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/rest/actions/service/GenerateRestMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/GenerateMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/operation/AddOperationAsMockResponseStepAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/request/AddRequestAsMockResponseStepAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/request/AddRequestToMockServiceAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-307

SOAPUIOS-307 No event for the creation of mock service from Navigator

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/support/ProcessToolRunner.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/wsi/WSIAnalyzeAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/mockoperation/actions/WSIValidateResponseAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/request/actions/WSIValidateRequestAction.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUILoadTestRunner.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUISecurityTestRunner.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUITestCaseRunner.java

https://smartbear.atlassian.net/browse/SOAPUIOS-296

SOAPUIOS-296 Duplicated launch runner event

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/testcase/AddNewLoadTestAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-318
https://smartbear.atlassian.net/browse/SOAPUIOS-319

SOAPUIOS-318, SOAPUIOS-319 Fix event's product area

---

soapui/src/main/java/com/eviware/soapui/impl/wsdl/panels/teststeps/PropertyTransfersDesktopPanel.java

https://smartbear.atlassian.net/browse/SOAPUIOS-317

SOAPUIOS-317 Send event after adding new property transfer

---

soapui/pom.xml
soapui/src/main/java/com/eviware/soapui/impl/wsdl/submit/transports/http/HttpClientRequestTransport.java

https://smartbear.atlassian.net/browse/SOAPUIOS-285

SOAPUIOS-285 Redirect does not work for get request

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/support/editor/inspectors/auth/ProfileSelectionForm.java

https://smartbear.atlassian.net/browse/SOAPUIOS-316

SOAPUIOS-316 Add events for every auth type

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/testcase/AddWsdlTestStepAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/teststep/InsertWsdlTestStepAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-320

SOAPUIOS-320 Change contextMenuAddNewTestStep event

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/project/AddNewMockServiceAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/project/AddNewRestMockServiceAction.java

https://smartbear.atlassian.net/browse/SOAPUIOS-308

SOAPUIOS-308 Rename new mock events

---

soapui/src/main/java/com/eviware/soapui/analytics/SoapUIActions.java
soapui/src/main/java/com/eviware/soapui/impl/rest/actions/method/NewRestRequestAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/soapui/LoadTestRunnerAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/soapui/TestRunnerAction.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/support/ProcessToolRunner.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/actions/iface/tools/support/SecurityTestRunnerAction.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUILoadTestRunner.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUISecurityTestRunner.java
soapui/src/main/java/com/eviware/soapui/tools/SoapUITestCaseRunner.java

https://smartbear.atlassian.net/browse/SOAPUIOS-322
https://smartbear.atlassian.net/browse/SOAPUIOS-325
https://smartbear.atlassian.net/browse/SOAPUIOS-326
https://smartbear.atlassian.net/browse/SOAPUIOS-327
https://smartbear.atlassian.net/browse/SOAPUIOS-323
https://smartbear.atlassian.net/browse/SOAPUIOS-324
https://smartbear.atlassian.net/browse/SOAPUIOS-321

 SOAPUIOS-322,  SOAPUIOS-325,  SOAPUIOS-326,  SOAPUIOS-327,  SOAPUIOS-323,  SOAPUIOS-324, SOAPUIOS-321 Fix bunch of analytics issue

---

soapui/src/main/java/com/eviware/soapui/tools/SoapUIToolRunner.java

https://smartbear.atlassian.net/browse/SOAPUIOS-330

SOAPUIOS-330 no event tracked after running toolrunner

---

soapui/src/main/java/com/eviware/soapui/actions/SumbitUserInfoAction.java
soapui/src/main/java/com/eviware/soapui/analytics/Analytics.java
soapui/src/main/java/com/eviware/soapui/analytics/AnalyticsHelper.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/OSUserProvider.java
soapui/src/main/java/com/eviware/soapui/analytics/providers/OSUserProviderFactory.java

https://smartbear.atlassian.net/browse/SOAPUIOS-268
https://smartbear.atlassian.net/browse/SOAPUIOS-286

SOAPUIOS-268-Redirect-analytics-data

---

soapui/src/main/java/com/eviware/soapui/analytics/Analytics.java

https://smartbear.atlassian.net/browse/SOAPUIOS-336

SOAPUIOS-336 can't import api from swagger hub

---

soapui/src/main/java/com/eviware/soapui/SoapUI.java
soapui/src/main/java/com/eviware/soapui/impl/wsdl/support/HelpUrls.java

https://smartbear.atlassian.net/browse/SOAPUIOS-239

SOAPUIOS-239 Not exisitng page is opened in browser on first run

---

soapui/src/main/java/com/eviware/soapui/impl/rest/RestMockResultMessageExchange.java
soapui/src/main/java/com/eviware/soapui/impl/rest/mock/RestMockResult.java

Fix for: https://community.smartbear.com/t5/SoapUI-Open-Source/Message-Viewer-Not-Working/td-p/139859

SOAPUIOS-582 Fix rest mock service message viewer

---

README.md

Updated Additional resources
